######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 4 13:41:56 2016
######################################################################

TEMPLATE = app
TARGET = atlas
DEPENDPATH += .
INCLUDEPATH += .
QT += sql widgets
QT += testlib

# Input
INCLUDEPATH += ./src
INCLUDEPATH += ./include
INCLUDEPATH += ./languages
INCLUDEPATH += ./ui
QMAKE_CXX_FLAGS += -std=c++11

HEADERS += \
    ../general_gui_files/include/filetotabwidget.h \
    include/integratormainwindow.h \
    ../general_gui_files/include/generalwindow.h \
    ../general_gui_files/include/printelement.h \
    ../general_gui_files/include/shell.h \
    ../general_gui_files/include/startwindow.h \
    ../general_gui_files/include/userrecord.h \
    include/integratorwidget.h \
    ../general_gui_files/include/textdialog.h \
    include/integratorsshworker.h \
    include/tableintegrelem.h

FORMS += ui/mainwindow.ui

SOURCES += src/main.cpp \
    ../general_gui_files/src/filetotabwidget.cpp \
    ../general_gui_files/src/generalwindow.cpp \
    ../general_gui_files/src/printelement.cpp \
    ../general_gui_files/src/shell.cpp \
    ../general_gui_files/src/startwindow.cpp \
    ../general_gui_files/src/userrecord.cpp \
    src/integratormainwindow.cpp \
    src/integratorwidget.cpp \
    ../general_gui_files/src/textdialog.cpp \
    src/integratorsshworker.cpp

TRANSLATIONS += languges/main_ru.ts \
                languges/main_en.ts
